# mosdns v5.3.x
# 2024/01/28
#
log:
  level: debug
  file: "/var/log/mosdns.log"

api:
  http: "0.0.0.0:9091"

include: []

plugins:
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_cn.txt"
        - "/var/mosdns/geosite_apple-cn.txt"
        - "/var/mosdns/geosite_icloud.txt"
        - "/var/mosdns/geosite_google-cn.txt"
        - "/var/mosdns/geosite_tld-cn.txt"

  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/mosdns/geoip_cn.txt"

  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/var/mosdns/geosite_geolocation-!cn.txt"

  - tag: whitelist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/whitelist.txt"

  - tag: blocklist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/blocklist.txt"

  - tag: greylist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/greylist.txt"

  - tag: ddnslist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/ddnslist.txt"

  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"

  - tag: redirect
    type: redirect
    args:
      files:
        - "/etc/mosdns/rule/redirect.txt"

  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/local-ptr.txt"

  - tag: cloudflare_cidr
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rule/cloudflare-cidr.txt"

  # 缓存，设置小缓存，主缓存由ADG做
  - tag: lazy_cache
    type: cache
    args:
      size: 2048
      lazy_cache_ttl: 1800

# 方案一: mosdns 不仅分流,自己做查询 {{{1
#
#  - tag: forward_local
#    type: forward
#    args:
#      concurrent: 2
#      upstreams:
#        - addr: "https://dns.alidns.com/dns-query"
#          dial_addr: "223.5.5.5"
#          bootstrap: ""
#          idle_timeout: 30
#          enable_pipeline: true
#          enable_http3: false
#          max_conns: 2
#          insecure_skip_verify: false
#          so_mark: 0
#          bind_to_device: ""
#        - addr: "https://doh.pub/dns-query"
#          dial_addr: "1.12.12.12"
#          bootstrap: ""
#          idle_timeout: 30
#          enable_pipeline: true
#          enable_http3: false
#          max_conns: 2
#          insecure_skip_verify: false
#          so_mark: 0
#          bind_to_device: ""
#
#  - tag: forward_remote
#    type: forward
#    args:
#      concurrent: 2
#      upstreams:
#        - addr: "https://dns.google/dns-query"
#          dial_addr: "8.8.8.8"
#          bootstrap: ""
#          socks5: "127.0.0.1:7891"
#          idle_timeout: 30
#          enable_pipeline: true
#          enable_http3: false
#          max_conns: 2
#          insecure_skip_verify: false
#          so_mark: 0
#          bind_to_device: ""
#        - addr: "https://1.0.0.1/dns-query"
#          dial_addr: "1.0.0.1"
#          bootstrap: ""
#          socks5: "127.0.0.1:7891"
#          idle_timeout: 30
#          enable_pipeline: true
#          enable_http3: false
#          max_conns: 2
#          insecure_skip_verify: false
#          so_mark: 0
#          bind_to_device: ""
#
# }}}

# 方案二，上游ADG做实际查询,mosdns只做分流 {{{1
#
  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "udp://192.168.5.149:53"
          idle_timeout: 30
          enable_pipeline: false
          max_conns: 2

  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "udp://192.168.5.148:53"
          idle_timeout: 30
          enable_pipeline: false
          max_conns: 2
#
# }}}

  - tag: forward_remote_upstream
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote

  - tag: modify_ttl
    type: sequence
    args:
      - exec: ttl 0-0

  - tag: modify_ddns_ttl
    type: sequence
    args:
      - exec: ttl 5-5

  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $modify_ddns_ttl
      - matches: "!qname $ddnslist"
        exec: $modify_ttl
      - matches: has_resp
        exec: accept

  - tag: query_is_non_local_ip
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp

  - tag: fallback
    type: fallback
    args:
      primary: forward_remote_upstream
      secondary: forward_remote_upstream
      threshold: 500
      always_standby: true

  - tag: query_is_ddns_domain
    type: sequence
    args:
      - matches: qname $ddnslist
        exec: $forward_local

  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $forward_local

  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $forward_remote_upstream

  - tag: query_is_whitelist_domain
    type: sequence
    args:
      - matches: qname $whitelist
        exec: $forward_local

  - tag: query_is_greylist_domain
    type: sequence
    args:
      - matches: qname $greylist
        exec: $forward_remote_upstream

  - tag: query_is_reject_domain
    type: sequence
    args:
      - matches: qname $blocklist
        exec: reject 3
      - matches:
        - qtype 12
        - qname $local_ptr
        exec: reject 3
      - matches: qtype 65
        exec: reject 3

  - tag: main_sequence
    type: sequence
    args:
      - exec: $hosts
      - exec: jump has_resp_sequence
      - matches:
        - "!qname $ddnslist"
        - "!qname $blocklist"
        - "!qname $local_ptr"
        exec: $lazy_cache
      - exec: $redirect
      - exec: jump has_resp_sequence
      - exec: $query_is_ddns_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_whitelist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_reject_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_greylist_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback

  # 监听在环回地址上，不对外开放
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: "127.0.0.1:5335"

  # 监听在环回地址上，不对外开放
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: "127.0.0.1:5335"
