# openwrt openclash config
# 2024/01/28
#
# clash conf {{{1
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
# dns port:7894
tproxy-port: 7895
ipv6: false
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
# }}}

# dns {{{1
dns:
  enabled: false
  listen: 0.0.0.0:7894
  ipv6: false
  enhanced-mode: redir-host
  enable: true
  nameserver:
    # use mosdns upstream
    - 127.0.0.1:5335
# }}}


# proxies {{{1
proxies:
  - {"name":"hk-reality-5432","type":"vless","server":"192.168.5.10","port":5432,"udp":true,"uuid":"11111111-1111-1111-1111-111111111111","tls":true,"servername":"www.amazon.com","flow":"xtls-rprx-vision","network":"tcp","reality-opts":{"public-key":"KEY1111111111111111111111111111111111111111"},"client-fingerprint":"ios"}
  - {"name":"hk-reality-15432","type":"vless","server":"192.168.5.10","port":15432,"udp":true,"uuid":"22222222-2222-2222-2222-222222222222","tls":true,"servername":"www.ebay.com","flow":"xtls-rprx-vision","network":"tcp","reality-opts":{"public-key":"KEY2222222222222222222222222222222222222222"},"client-fingerprint":"ios"}
  - {"name":"us-reality-5432","type":"vless","server":"192.168.5.11","port":5432,"udp":true,"uuid":"33333333-3333-3333-3333-333333333333","tls":true,"servername":"www.amazon.com","flow":"xtls-rprx-vision","network":"tcp","reality-opts":{"public-key":"KEY3333333333333333333333333333333333333333"},"client-fingerprint":"ios"}
# }}}


# proxy groups {{{1
proxy-groups:
  - name: MANUALLY
    type: select
    proxies:
      - AUTOPROXY
      - DIRECT
      - hk-reality-5432

  - name: AUTOPROXY
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - hk-reality-5432
      - hk-reality-15432

  - name: DEFAULT
    type: select
    proxies:
      - AUTOPROXY
      - DIRECT

  - name: GPT_hk2us
    type: select
    proxies:
      - us-reality-5432
# }}}


# rule providers {{{1
rule-providers:
  # 广告域名
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  # icloud 域名
  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  # apple 中国大陆可访问域名
  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  # 代理域名
  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  # 直连域名
  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  # 私有网络专用域名
  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  # gfw list
  gfw:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  # 非中国大陆使用顶级域名
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  # tg ip
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  # 中国大陆ip
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  # 局域网ip与保留ip
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  # 需要直连的常见app
  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
# }}}


# rules {{{1
rules:
  # manual rule {{{1
  - DOMAIN-SUFFIX,openai.com,GPT_hk2us
  - DOMAIN-SUFFIX,auth0.com,GPT_hk2us
  - DOMAIN-SUFFIX,shodan.io,AUTOPROXY
  # }}}
  - RULE-SET,reject,REJECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,proxy,AUTOPROXY
  - RULE-SET,telegramcidr,AUTOPROXY
  - MATCH,DEFAULT
# }}}
